version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    # --hostオプションがついてないとサーバー立ててもアクセスできないよ
    command: >
      bash -c "yarn dev --host"
    volumes:
      - ./:/react_test_app
    ports:
      - "3000:3000"